### ISSUE TITLE
Exception running remover

### ISSUE THREAD

**Issue by BryanFauble** [azaghal/factorio-biter-remover#1]
https://github.com/azaghal/factorio-biter-remover/blob/834588504a56963f36513c057201694403ee7748/scripts/remover.lua#L63

Command run:
`/disable-biter-base-generation [SURFACE]`

This line is throwing an exception:
![image](https://user-images.githubusercontent.com/17128019/200963382-d671b41b-a94f-4582-8c0b-2511289431df.png)

Mods installed:
![image](https://user-images.githubusercontent.com/17128019/200963468-fbea05a3-0940-4f84-afb6-0e9f235138d6.png)
![image](https://user-images.githubusercontent.com/17128019/200963499-b78bf8b1-060f-4e6e-bfe0-786de3ccb5e0.png)

**Comment by azaghal** [comment]
Thank you for reporting the bug, and sorry for a lack of responsiveness on my side. I'll try to have a look at it, although I have a small question for you.

Was the command you listed the exact thing you typed-in when the crash happened? Or did you supply a specific surface name (I wonder if I test properly in the code for invalid/nonexistent surface names, will have to check that)?

**Comment by azaghal** [comment]
Ok, so I wasn't able to reproduce the issue locally using Space Exploration, although not with all the mods you listed here. 

1. What was the exact surface that you have run the command against?
2. What game version were you using?
3. Can you provide me with a savegame where this is easily reproducible?

**Comment by azaghal** [comment]
Ok, after having a look at the mods you have installed, I noticed Factorissimo 2 and, after trying out the command against factory surface, managed to reproduce the crash.

I'll introduce some logic around that to skip surfaces that lack the missing property.

**Comment by azaghal** [comment]
Fixed in version 1.1.1, I'll mark the issue as resolved. If the issue persists for you, just drop me a comment and I'll have another look at it.

Thank you once again for reporting the crash :)
